## mini-batch 全连接层变换

In [3]:
import numpy as np

W1 = np.random.randn(2, 4)  # 权重
b1 = np.random.randn(4)  # 偏置
x = np.random.randn(10, 2)  # 输入
h = np.dot(x, W1) + b1  # 输出
print('W1:', W1)
print('b1:', b1)
print('x:', x)
print('h:', h)

W1: [[ 0.9416318  -0.64799101 -0.45185271 -0.77176706]
 [ 0.40080749  1.11759626  1.04142664 -0.68003073]]
b1: [-0.49873995 -0.9841951   1.24463856 -1.13535769]
x: [[ 1.05323456 -0.85019993]
 [-0.93076605  0.2995948 ]
 [ 1.09565234 -0.7668491 ]
 [-1.32827663 -1.48286517]
 [ 2.14935801  0.9252244 ]
 [ 1.40884781 -3.24736826]
 [ 0.38565974 -0.88123179]
 [ 1.7714928  -1.11777465]
 [ 0.75044435 -0.98877027]
 [ 1.77220707  0.25639455]]
h: [[ 0.15225271 -2.61686188 -0.11668918 -1.37004736]
 [-1.25509902 -0.04624103  1.97721372 -0.62075677]
 [ 0.22560228 -2.55119565 -0.049052   -1.45946512]
 [-2.34383093 -1.78072834  0.30052866  0.89815634]
 [ 1.89600079 -1.34293245  1.23699866 -3.42334243]
 [-0.47369357 -5.52636243 -2.77384894 -0.01434982]
 [-0.48879477 -2.21896049  0.1526389  -0.83373248]
 [ 0.72134156 -3.38132728 -0.71989555 -1.74241637]
 [-0.18840422 -2.57552225 -0.12418345 -1.04213175]
 [ 1.27279144 -1.84602377  0.71087811 -2.6774449 ]]


## 激活函数 sigmoid
公式 ![1_2_1](images/1_2_1.png)

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


a = sigmoid(h)
print(a)


[[0.53798982 0.06806107 0.47086076 0.2026122 ]
 [0.22181872 0.4884418  0.87838383 0.34960935]
 [0.55616257 0.0723462  0.48773946 0.18854915]
 [0.08755737 0.14421322 0.57457175 0.71057048]
 [0.86943822 0.20702823 0.77504116 0.03157387]
 [0.3837424  0.00396466 0.0587538  0.49641261]
 [0.38017753 0.09806071 0.53808581 0.30285644]
 [0.67290237 0.03288416 0.32741598 0.14900627]
 [0.45303778 0.07073048 0.46899397 0.26073888]
 [0.78122022 0.13634043 0.67059516 0.06431747]]


In [6]:
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
s = np.dot(a, W2) + b2
print(s)

[[-0.07904049 -0.56835672 -1.8134415 ]
 [ 0.64708441 -0.4230705  -1.2505176 ]
 [-0.09519843 -0.54528765 -1.84863312]
 [ 0.71694833 -0.96117952 -1.13257288]
 [-0.24486242 -0.19355281 -2.48263851]
 [ 0.14805367 -1.02489239 -1.52715385]
 [ 0.1357823  -0.63351535 -1.54520349]
 [-0.25658081 -0.57879202 -2.03527524]
 [ 0.02234884 -0.62815622 -1.66286158]
 [-0.24463811 -0.30505572 -2.29879063]]


## 层的类化 及 正向传播的实现
要实现的神经网络的层结构：![1_2_2](images/1_2_2.png)

In [7]:
import numpy as np


class Sigmoid(object):
    def __init__(self):
        self.params = []

    @staticmethod
    def forward(x):
        return 1 / (1 + np.exp(-x))


class Affine(object):
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        return np.dot(x, W) + b


class TwoLayerNet(object):
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 初始化权重、偏置
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 实例化生成层
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2),
        ]

        # 将所有权重整理到列表
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(x)

[[ 0.32307519  0.41744942]
 [ 0.90695764  0.10402527]
 [-0.04666013 -1.14108063]
 [-1.85593069 -1.35711604]
 [-1.10538726  0.10994757]
 [-0.29413759  2.28412037]
 [ 0.19546998 -0.43150058]
 [ 0.64890816 -0.27846305]
 [ 0.34213044  0.82987159]
 [-2.18714755  1.12124173]]
